version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: mts-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7
    container_name: mts-redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    container_name: mts-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trading
    ports:
      - "5432:5432"